# Generated by Django 4.2.21 on 2026-06-26 08:16

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('data_scientist', 'Data Scientist'), ('student', 'Student'), ('researcher', 'Researcher'), ('company', 'Company')], default='student', help_text='User role determines permissions and default quotas.', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, help_text='User profile photo (recommended: 256×256 px).', null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, default='', help_text='Short biography or description.', max_length=500)),
                ('institution', models.CharField(blank=True, default='', help_text='University, company, or research institution.', max_length=200)),
                ('github_url', models.URLField(blank=True, default='', help_text='Link to GitHub profile.', max_length=300, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, default='', help_text='Link to LinkedIn profile.', max_length=300, verbose_name='LinkedIn URL')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether the user has verified their email address.')),
                ('dataset_quota', models.IntegerField(default=5, help_text='Maximum number of datasets allowed. -1 means unlimited.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'intellihub_users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
