# Generated by Django 4.2.21 on 2026-06-26 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('dense_nn', 'Dense Neural Network'), ('simple_cnn', 'Simple CNN')], default='dense_nn', max_length=20)),
                ('target_column', models.CharField(max_length=100)),
                ('feature_columns', models.JSONField(default=list)),
                ('architecture', models.JSONField(default=list)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('training_history', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('model_file', models.FileField(blank=True, upload_to='dl_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_models', to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intellihub_dl_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
