# Generated by Django 4.2.21 on 2026-06-26 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable model name.', max_length=255)),
                ('model_type', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('multiple_regression', 'Multiple Regression'), ('polynomial_regression', 'Polynomial Regression'), ('ridge', 'Ridge Regression'), ('lasso', 'Lasso Regression'), ('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree'), ('random_forest', 'Random Forest'), ('knn', 'K-Nearest Neighbors'), ('svm', 'Support Vector Machine'), ('naive_bayes', 'Naive Bayes')], help_text='Algorithm used for training.', max_length=30)),
                ('target_column', models.CharField(help_text='Name of the target / label column.', max_length=255)),
                ('feature_columns', models.JSONField(default=list, help_text='List of feature column names used for training.')),
                ('model_file', models.FileField(blank=True, help_text='Serialised model artefact (pickle).', upload_to='models/')),
                ('metrics', models.JSONField(default=dict, help_text='Evaluation metrics dict — e.g. accuracy, f1, precision, recall, r2, mae, rmse, confusion_matrix.')),
                ('test_size', models.FloatField(default=0.2, help_text='Fraction of data reserved for testing (0–1).')),
                ('hyperparameters', models.JSONField(default=dict, help_text='Model-specific hyperparameters used during training.')),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether the user has starred this model.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(help_text='Source dataset used for training.', on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='datasets.dataset')),
                ('user', models.ForeignKey(help_text='Owner of this ML model.', on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'db_table': 'intellihub_ml_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Feature values supplied for prediction.')),
                ('predicted_value', models.JSONField(help_text='Model output (scalar or probability array).')),
                ('confidence', models.FloatField(blank=True, help_text='Prediction confidence / probability (classification only).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(help_text='The ML model that produced this prediction.', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_studio.mlmodel')),
                ('user', models.ForeignKey(help_text='User who requested this prediction.', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'db_table': 'intellihub_predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
