# Generated by Django 4.2.21 on 2026-06-26 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_applied', models.JSONField(default=list)),
                ('rows_before', models.IntegerField(default=0)),
                ('rows_after', models.IntegerField(default=0)),
                ('quality_before', models.FloatField(default=0.0)),
                ('quality_after', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_logs', to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intellihub_cleaning_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
