# Generated by Django 4.2.21 on 2026-06-26 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('dataset_summary', 'Dataset Summary'), ('full_analysis', 'Full Analysis'), ('ml_report', 'ML Report'), ('custom', 'Custom')], default='dataset_summary', max_length=20)),
                ('report_file', models.FileField(upload_to='reports/')),
                ('sections', models.JSONField(default=list)),
                ('page_count', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intellihub_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
